server:
  port: '8081'
  
spring:
  config:
    activate:
      on-profile: prod
  application:
    name: blackyakb2c-prod
  datasource:
  #DB설정
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@121.254.249.72:9521:YAKERP
    username: US_B2C    
    password: US_B2C
  jpa:    
    open-in-view: false
    database: oracle
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        '[format_sql]': true

      

    
    
    
    


    
