 spring:
  profiles:
      default: local
  application:
    name: blackyakb2c-prod
  datasource:
  #DB설정
    driver-class-name: oracle.jdbc.driver.OracleDriver
    username: US_B2C    
    password: US_B2C
  jpa:    
    open-in-view: false
    database: oracle
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        '[format_sql]': true     

    
    
    
    


    
