server:
  port: '8080'
  
spring:
  datasource:
  #DB설정
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@121.254.249.72:9521:YAKERP
    username: US_B2C    
    password: US_B2C

      
mybatis:
#Xml
  mapper-locations: classpath:mapper/*.xml
#Dto
  type-aliases-package: com.blackyak.b2c.api.product.mapper.dto

